### PR TITLE
Fix bug caused by desynced projection overculling

### PR DESCRIPTION
**Pull request by TheRawMeatball**

### CODE REVIEW

**Review by bonsairobo — APPROVED** [review]
Makes sense why this fixes the bug.

I wonder if there is a way to avoid the duplicate camera entity in the first place. AFAICT there is an `InternalGizmoCamera` entity because the gizmo always wants to be rendered last. This is accomplished by using render layer 12 and loading a zeroed out depth buffer specifically for that render layer.

Maybe instead this could be accomplished with a new feature inside of `bevy_render` that allows the gizmo to be rendered in the default layer. I think this would require a couple changes:

- a specialized pipeline that uses `CompareFunction::Always`
- a maximal `PhaseItem::SortKey` value

Then the gizmo would always be drawn last, and it would never fail the depth test.

**Comment by TheRawMeatball** [comment]
> a maximal `PhaseItem::SortKey` value

Issue with this approach is it breaks sorting between the elements of the gizmo.

**Comment by bonsairobo** [comment]
> > a maximal `PhaseItem::SortKey` value
> 
> Issue with this approach is it breaks sorting between the elements of the gizmo.

Good point. I guess they really do need their own depth buffer.

**Comment by bonsairobo** [comment]
Ready to merge?

**Comment by TheRawMeatball** [comment]
@aevyrie can you merge this and cut a release?

**Review by aevyrie — APPROVED** [review]

**Pull request merged**
